package com.satux.duax.tigax.utils;

public interface Config {

    String TEMP_URL = "https://api.soundcloud.com/tracks/";
    String TEMPS_URL = "http://api.soundcloud.com/tracks.json?client_id=";
    String PLAYING_TAG = "/stream?client_id=";
    String DB_NAME = "data_fave.db";
    String TABLE_NAME = "datafave";
    String CLIENT_ID = "key";
    String TYPE = "text/plain";
    String TAGs = "&q=";
    String PREF = "MY_PREF";
    String A15 = "415";
    String SHARE_APP = "Share This App";
    String OK = "Ok";
    String NOW_PLAYING = "Now Playing";
    String T_PRIVACY = "Privacy Policy";
    String PRIVACY = "<html><MainActivity>1.</MainActivity> Our policy is not to collect or store any personal information about the users of our Android Applications.<br/><br/><MainActivity>2.</MainActivity> Our Applications do not collect and send any personal information to us.<br/><br/><MainActivity>3.</MainActivity> Our <u>free to use</u> Applications may display <u>admob, by Google</u> banner advertising. Our applications link to the admob advertising service, using their application interface. The collection and use of personal data by the admob service is covered by the <u>admob, by Google</u> privacy policy.  Please see their privacy policy (http://www.admob.com/home/privacy). Our Applications link with the admob service making use of TRG7690 minimal interface that permits the display of banner advertising. Our Applications do not provide any of your personal information to the admob service (MainAdapter.MainConnect. we do not tell admob anything about you, to enable them to target advertising based on your profile). Our applications include access permissions (MainAdapter.MainConnect. internet access) in order to display the admob advertising.<br/><br/><MainActivity>4.</MainActivity> We have access to limited and anonymous statistical information about the use of our Applications from Google Play and admob by Google.<br/><br/><MainActivity>5.</MainActivity> We may store and use for business purposes any information that is received by email, etc. We will manage this information in accordance with the ID Data Protection Act and ID law.</html>";
    String T_DISCLAIMER = "Disclaimer";
    String DISCLAIMER = "<html>This is an unofficial apps free for Download.<br/><br/>This apps and its content are not officially endorsed or produced by, nor associated with or affiliated with the music artist(s)or any associated entities of the artist(s), such as management or record label.<br/><br/>All trademarks and copyrights are property of their respective owners. This application has ads that comply with Google Play Policy and Please support the artists and their companies.</html>";
    String offset = "&offset=";
    String limit = "&limit=20";
    String POINT = "POINT";
    String D_POINT = "🌀  Download Point : ";
    String E_POINT = "  🌀";
    String T_RATE = "Rate This App!";
    String X_RATE = "Later";
    String R_RATE = "Rate";
    String P_RATE = "If you enjoy playing this app, would you mind taking a moment to rate it? It won\'t take more than a minute. Thanks for your support!";
    String G_GENRE = "[{\"name\":\"all-music\"},{\"name\":\"Alternative Rock\"},{\"name\":\"Ambient\"},{\"name\":\"Classical\"},{\"name\":\"Country\"},{\"name\":\"Dance & EDM\"},{\"name\":\"Dancehall\"},{\"name\":\"Deep House\"},{\"name\":\"Disco\"},{\"name\":\"Drum & Bass\"},{\"name\":\"Dubstep\"},{\"name\":\"Electronic\"},{\"name\":\"Folk & Singer-Songwriter\"},{\"name\":\"Hip-hop & Rap\"},{\"name\":\"House\"},{\"name\":\"Indie\"},{\"name\":\"Jazz & Blues\"},{\"name\":\"Latin\"},{\"name\":\"Metal\"},{\"name\":\"Piano\"},{\"name\":\"Pop\"},{\"name\":\"R&B & Soul\"},{\"name\":\"Reggae\"},{\"name\":\"Reggaeton\"},{\"name\":\"Rock\"},{\"name\":\"Soundtrack\"},{\"name\":\"Techno\"},{\"name\":\"Trance\"},{\"name\":\"Trap\"},{\"name\":\"Triphop\"},{\"name\":\"World\"},{\"name\":\"Dangdut\"},{\"name\":\"Hindi\"},{\"name\":\"Melayu\"}]";
    String L_RATE = "market://details?id=";
    String L_SHARE = "https://play.google.com/store/apps/details?id=";
    String a1 = "id";
    String a2 = "title";
    String a3 = "duration";
    String a4 = "original_content_size";
    String a4a = "size";
    String a5 = "likes_count";
    String a5a = "love";
    String a6 = "artwork_url";
    String a6a = "image";
    String a57 = "soundcloud";
    String b1 = "Download in progress";
    String b2 = "Please Wait!";
    String b3 = ".mp3";
    String b4 = "Downloaded Successfully";
    String c1 = "Tap Image to Play Music";
    String c2 = "Buffering...";
    String c3 = "Press Button Download Again";
    String c4 = "Allow Permission For Download";
    String c5 = "Write External Storage permission allows us to do store Music. Please allow this permission in App Settings.";
    String c6 = "Favorite Saved";
    String c7 = "Remove Success";
    String d1 = "Song Title";
    String d2 = "Song Info";
    String d3 = "400000";
    String d4 = "100";
    String d5 = "0";
    String d6 = "Please Connect Internet";
}
